spring.application.name=03-springai-docker-model-runner

spring.ai.openai.chat.model=ai/smollm2
spring.ai.openai.base-url=http://localhost:12434/engines/v1

# To use local running models, spring team has decided to use the same api as for openai.
# So api-key is needed by the api.
spring.ai.openai.api-key=dummy
