spring.application.name=03-springai-aws-bedrock

spring.ai.bedrock.aws.region=
spring.ai.bedrock.aws.access-key=${AWS_ACCESS_KEY}
spring.ai.bedrock.aws.secret-key=${AWS_SECRET_KEY}

spring.ai.model.chat=bedrock-converse
spring.ai.bedrock.converse.chat.model=${AWS_CHAT_MODEL}
