spring:
  application:
    name: 08-springai-advisor
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-5-nano

logging.level.org.springframework.ai.chat.client.advisor: DEBUG
